name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Welcome1234
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: install go-lang migrate
        env:
          MIGRATE_VERSION: v4.17.0
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/$MIGRATE_VERSION/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: rung migrations
        run: make migrateup
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Test
        run: make test
